### PR TITLE
Directly inheriting from ActiveRecord::Migration is not supported in Rails 5.1

### PR DESCRIPTION
**Pull request by abreckner**
More info here:
https://github.com/ilyakatz/data-migrate/issues/53
https://github.com/RolifyCommunity/rolify/issues/444

### CODE REVIEW

**Comment by abreckner** [comment]
Re-opening to test new solution.

**Comment by jturkel** [comment]
@abreckner - I'm not a maintainer on this project but I can't find any reference to the `DataMigrate::Migration` class in the codebase. I tried commenting it out and all tests passed and the gem seemed to work with some manual testing. Maybe this is deadcode that can be removed?

**Comment by abreckner** [comment]
@jturkel you could be right. I just copied the original `migration.rb` file and changed the opening `class` statement so it's compatible with Rails 5.1 (i.e. it adds a version number to the inheritance).

**Comment by dorner** [comment]
+1 - can't use this with Rails 5.1 until this is merged.

**Comment by ilyakatz** [comment]
@jturkel test coverage for this gem is pretty bad (I'm trying to add more as I go) so it cannot be trusted. migration.rb is very much used - this is how data migrations wind up in their own table instead of being intermixed with schema migrations. I started a new PR that incorporates this change and adds some tests #61. Can you and @abreckner let me know your thoughts?

**Comment by ilyakatz** [comment]
Version 3.1.0 pushed to rubygems https://rubygems.org/gems/data_migrate/versions/3.1.0

**Pull request closed without merging**
