### PR TITLE
Fixes #201 - fixed`db:migrate:with_data` to compare data schema versions correctly

### LINKED ISSUE #201: Wrong value for `current_data_version` in `db:migrate:with_data`?
In the blob: 
https://github.com/ilyakatz/data-migrate/blob/1db042bfd1f29602dffe27b233e3261fa7eb7bb4/tasks/databases.rake#L13-L46

The following variables are currently assigned to the same value:
https://github.com/ilyakatz/data-migrate/blob/1db042bfd1f29602dffe27b233e3261fa7eb7bb4/tasks/databases.rake#L16
https://github.com/ilyakatz/data-migrate/blob/1db042bfd1f29602dffe27b233e3261fa7eb7bb4/tasks/databases.rake#L25

I think Line 25 is supposed to read
```
current_data_version = DataMigrate::DataMigrator.current_version
```

Haven't gone through testing yet, but wanted to see if anyone else thought this was incorrect?

### PR DESCRIPTION
**Pull request by sully7**
#201

### CODE REVIEW

**Comment by sully7** [comment]
also fixes #117

**Comment by ilyakatz** [comment]
https://github.com/ilyakatz/data-migrate/issues/201#issuecomment-1006849161

**Comment by ilyakatz** [comment]
Cherry-picked in https://github.com/ilyakatz/data-migrate/pull/218!

Thanks for the contributions

**Comment by reidab** [comment]
This ended up getting grouped in with changes from #211 in the 8.1.0 release, which was then completely reverted. This change is still needed.

**Comment by ilyakatz** [comment]
You're right, thanks for the bump. Just released on it's own via https://github.com/ilyakatz/data-migrate/pull/235

**Comment by reidab** [comment]
@ilyakatz It doesn't look like that PR contains this fix. It's still pulling the current data version from `ActiveRecord::Migrator.current_version` instead of `DataMigrate::DataMigrator.current_version` here https://github.com/ilyakatz/data-migrate/blob/88d4737e904b99299dff48d085189cadd1f1e2a2/tasks/databases.rake#L25  in that PR branch.

**Comment by ilyakatz** [comment]
hm, @reidab, would you be interested to create a PR?

**Comment by reidab** [comment]
@ilyakatz done — here's a re-creation of this PR against the current head: https://github.com/ilyakatz/data-migrate/pull/239

**Pull request closed without merging**
