### PR TITLE
Rails5 support

### PR DESCRIPTION
**Pull request by ilyakatz**
Building up on #52

### CODE REVIEW

**Comment by jturkel** [comment]
Out of curiosity where is the `DataMigrate::MigrationFive` class used other than test code?

**Comment by ilyakatz** [comment]
I was following the suggestion in the original PR - if running under Rails5 it will load that file, else it will load the old file. 

https://github.com/ilyakatz/data-migrate/pull/61/files#diff-dff88aaabf33d2956e9919de96673a4eR3

The test seem to confirm that this behavior works ok. 

Can you guys try it out under Rails5 app? I would like to hold off releasing the gem changes until someone has a change to try it out in a real app.

**Comment by jturkel** [comment]
I've been using a fork of this gem with the `DataMigrate::Migration` class removed in Rails 5.0 app for a few weeks and it seems to work fine. The `rake data:migrate`, `rake data:migrate:status` `rake data:migrate:rollback`, `rake db:migrate:with_data` work fine and the `data_migrations` table is maintained automatically. Is there anything in particular I should try testing that should use this code path?

**Comment by ilyakatz** [comment]
I did some refactoring/conflict resolutions so just want to make sure I didn’t screw anything up. So if you could try something against your rails 5 app just for sanity checking.

**Comment by jturkel** [comment]
The latest commit on master (ce9744bf1ca55cd18f0790d4e3e46f4441556fd7) works fine in my Rails 5.0.3 app.

**Comment by ilyakatz** [comment]
gem pushed https://rubygems.org/gems/data_migrate/versions/3.1.0

**Pull request merged**
