### PR TITLE
Ruby 3.2 compatibility

### PR DESCRIPTION
**Pull request by mehanoid**

### CODE REVIEW

**Comment by billabel** [comment]
@mehanoid I'm upgrading to 3.2, and looking over this PR to see if I need it this for rails 6.1. It looks like you are adding a fix for rails 5.2 compatibility. It's not clear since you don't have a commit message.

Can you confirm if this fix is only for rails 5.2?

Thanks!

**Comment by mehanoid** [comment]
@billabel This fix is not related to the rails version. It gets rid of the `File.exists` method call, which is removed from ruby 3.2.
While rails 5.2 is just excluded from the test suite for ruby 3.2 (as it was previously excluded also for 3.0), because it does not work with modern versions of ruby.

**Comment by ilyakatz** [comment]
Thanks for the PR. Looks like my CI stopped working (travis), so I had setup switched over to github actions and looks like there are some issues with Rails 5.2/Ruby 3.2 combo https://github.com/ilyakatz/data-migrate/actions/runs/4229593497/jobs/7346102107. It looks like rails 5.2 is EOL, right?  So wondering if we should stop supporting that instead of fixing the errors. Thoughts?

**Comment by mehanoid** [comment]
There were problems with Rails 5.2/Ruby 3.0 before, and this combo was already disabled in .travis.yml (accordingly, I disabled it for Ruby 3.2 as well). AFAIK this version of Rails itself has problems running on Ruby >= 3.0

At the same time, the Rails 5.2/Ruby 2.7 combo still works, although IMHO it's ok to support only still alive versions of Rails.

**Comment by ilyakatz** [comment]
merged via https://github.com/ilyakatz/data-migrate/pull/246, thanks for contributing!

**Pull request closed without merging**
