### PR TITLE
Error with db:migrate:status:with_data and data:migrate:status

### PR DESCRIPTION
**Pull request by gdott9**
Hello,

I have the following error when trying to get status with the last version 8.0.0.rc1 and Rails 7.0
```
NoMethodError: undefined method `[]' for #<ActiveRecord::DatabaseConfigurations:0x000055a720dc5808 @configurations=[#<ActiveRecord::DatabaseConfigurations::UrlConfig:0x000055a720dc55d8 @env_name="default", @name="primary", @configuration_hash={:encoding=>"unicode", :pool=>5, :adapter=>"postgresql", :username=>"[...]", :database=>"[...]", :host=>"localhost"}, @url="postgres://[...]@localhost/[...]">, #<ActiveRecord::DatabaseConfigurations::UrlConfig:0x000055a720ddaff0 @env_name="development", @name="primary", @configuration_hash={:encoding=>"unicode", :pool=>5, :adapter=>"postgresql", :username=>"[...]", :database=>"[...]", :host=>"localhost"}, @url="postgres://[...]@localhost/[...]">, #<ActiveRecord::DatabaseConfigurations::UrlConfig:0x000055a720dd9588 @env_name="test", @name="primary", @configuration_hash={:encoding=>"unicode", :pool=>5, :adapter=>"postgresql", :username=>"[...]", :database=>"[...]", :host=>"localhost"}, @url="postgres://[...]@localhost/[...]">, #<ActiveRecord::DatabaseConfigurations::UrlConfig:0x000055a720de3b00 @env_name="production", @name="primary", @configuration_hash={:encoding=>"unicode", :pool=>5, :adapter=>"postgresql", :username=>"[...]", :database=>"[...]", :host=>"localhost"}, @url="postgres://[...]@localhost/[...]">]>
./vendor/bundle/ruby/3.0.0/gems/data_migrate-8.0.0.rc1/tasks/databases.rake:275:in `block (3 levels) in <top (required)>' 
```

This PR moves the code for both data:migrate:status and db:migrate:status:with_data in `DataMigrate::Tasks::DataMigrateTasks`, adds tests for those tasks and correct the bug for Rails 7.0.

@ilyakatz Does this look good to you ?

### CODE REVIEW

**Comment by ilyakatz** [comment]
Thanks for flaggin! @daztmb does that seem correct to you?

**Comment by gdott9** [comment]
@ilyakatz Is it possible to merge this PR and release a new release candidate version ?

@slavakisel and @daztmb, as you have worked on rails 7 support, could you test this PR please ?
And thank you for the work you already did ! :+1:

**Comment by ilyakatz** [comment]
@gdott9 were you able to test it locally? if so, i'm ok released an rc2 (sorry, i don't have rails env's available right away to test :( )

**Comment by daztmb** [comment]
@gdott9 Thank you for continuing to support this gem. The changes look good for me. I have only 1 comment: for Rails 5.2, several specs fail:
rspec ./spec/data_migrate/tasks/data_migrate_tasks_spec.rb:151
rspec ./spec/data_migrate/tasks/data_migrate_tasks_spec.rb:157
could you try to fix it?

Perhaps @slavakisel will have something else to add

**Comment by gdott9** [comment]
@daztmb Thank you, I fixed the two failing specs.

@ilyakatz Yes, I tested it locally and I am using it in a production app with Ruby 3.0 and Rails 7.0.

**Comment by ilyakatz** [comment]
merged via #207 and new rc version released to rubygems. Thanks for the fix!

**Pull request merged**
