### PR TITLE
db:abort_if_pending_migrations:with_data and data:abort_if_pending_migrations

### PR DESCRIPTION
**Pull request by jturkel**
This PR adds `db:abort_if_pending_migrations:with_data` and `data:abort_if_pending_migrations` Rake tasks to mirror the Rails `db:abort_if_pending_migrations` Rake task.

### CODE REVIEW

**Comment by ilyakatz** [comment]
That's interesting. So is this responsible for failing various commands if schema (in this case, data) migration is not up to date? Will this be called internally by something or does it need to be called explicitly?

**Comment by jturkel** [comment]
We explicitly call `rake db:abort_if_pending_migrations` from a conditional in our deploy scripts to handle deploys with and without migrations slightly differently. Internally Rails also calls it from the `db:seed` Rake task. Here's the [source](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railties/databases.rake#L166) if you're interested.

**Comment by ilyakatz** [comment]
Oh, I see what this does. I'm a little hesitant about this change - rails does a hard stop if schema is not updated. however, for data that wouldn't always be the case. For example, if you run your tests, you don't necessarily need to run all data migrations. Any ideas?

**Comment by ilyakatz** [comment]
@jturkel do you have opinions on this? If not, i'll close it out. Trying to clean up PR's

**Comment by jturkel** [comment]
It's been awhile so I'm trying to remember the context here... It looks like this PR added two new rake tasks to return an error code if there pending data migrations. Unless I'm missing something it doesn't change any existing rake tasks so clients are free to use them or not use them in whatever context they want. The main use case for us was around deploy scripts that handle running schema + data migrations. I agree that for tests these new rake tasks don't make much sense but nothing would automatically invoke them in that scenario.

All that said, we decided to go a different direction with our data migrations so feel free to close this PR if you're not interested in pushing the change forward.

**Comment by whoisahmed** [comment]
@jturkel @ilyakatz Thanks for your work.
Do you know how can we show pending migration screen if we have pending data migration?

I tried aliasing:
```rb
  rake.alias "db:migrate", "db:migrate:with_data"
  rake.alias "db:rollback", "db:rollback:with_data"
  rake.alias "db:migrate:status", "db:migrate:status:with_data"
  rake.alias "db:version", "db:version:with_data"
  rake.alias "db:schema:load", "db:schema:load:with_data"
  rake.alias 'db:structure:load', 'db:structure:load:with_data'
  rake.alias "db:abort_if_pending_migrations", "db:abort_if_pending_migrations:with_data"
```
but it didn't work.

image

**Comment by vprigent** [comment]
Hi @whoisahmed 
Rails raises a special kind of error for their migration;
https://github.com/rails/rails/blob/f1be11af8e4294764ece2f1bfcf7f7bb7fae43ff/activerecord/lib/active_record/migration.rb#L697
I suspect you could monkey patch it in such a way that it raises the error if the data migrations haven't been run either.

**Comment by whoisahmed** [comment]
@vprigent thanks a lot!
I did it and works fine except that data_schema file got its version removed (`DataMigrate::Data.define()`), any thoughts?
image

**Comment by vprigent** [comment]
Can you open a PR with the patch? I should be able to have a look

**Pull request closed without merging**
