### PR TITLE
Fix use relative db/data path

### PR DESCRIPTION
**Pull request by Haradd**
Hi there!

I have a quite specific case. I've got defined migrations in the other project than I want to execute them.
Therefore, there's a problem with paths to the migrations, because they are searched in `first_project/db/data` while they are placed in `second_project/db/data`.
I decided to improve it.

I followed this example: https://github.com/ilyakatz/data-migrate/blob/master/lib/data_migrate/tasks/data_migrate_tasks.rb#L5
and use relative paths in some rake tasks.

However, there are many places where such relative path is also needed e.g `SchemaMigration`, `StatusService`.
I think we can define some `migration_path` method so that every service could use it.

What do you think about this problem and the solution? 🙂

### CODE REVIEW

**Comment by EnomaDebby** [comment]
Hi @Haradd, thanks for this. I'm working on something similar but in this case making the data migrate path to be configurable in the app using the gem. We can consolidate with your changes when I'm done.

**Comment by Haradd** [comment]
Hey  @EnomaDebby  👋 
How's it going? Do we have some estimated time of arrival?

**Comment by ilyakatz** [comment]
I believe #101 solves this issue, is that correct? If so, let's close this out

**Comment by Haradd** [comment]
yes, it's solved. Thanks a lot for helping!

**Pull request closed without merging**
