### PR TITLE
rspec tests

### PR DESCRIPTION
**Pull request by VagishVela**
So far added rspec and locked the gemfile. Now to add some tests.

### CODE REVIEW

**Comment by ilyakatz** [comment]
this looks like a good start. since this project has a rails dependency, you may be better off using https://github.com/rspec/rspec-rails, it has a nice generator that will create a spec_helper for you.

**Comment by VagishVela** [comment]
@ilyakatz I don't believe the generator works well with gems, it is more designed for rails projects. That's why I thought it makes sense to just use 'rspec' rather 'rpsec-rails'.

**Comment by ilyakatz** [comment]
ah ok, sounds good. let me know if you need anything from me

**Comment by ilyakatz** [comment]
@VagishVela I branched off your branch and added a couple of tests. do you want to merge it in and add more as you see fit? (my branch is https://github.com/ilyakatz/data-migrate/commits/tests)

**Comment by VagishVela** [comment]
@ilyakatz Should we merge this PR? And also could we add https://codeclimate.com/ and https://travis-ci.org/ both a free for OSS. Would be nice for future development...

**Comment by ilyakatz** [comment]
Merged. Travis doesn't seem to be working for me for now. Will take a look later. @VagishVela if you want to add more tests, that would be great. Thanks for starting this discussion

**Pull request merged**
