### PR TITLE
Removed pry dependency

### PR DESCRIPTION
**Pull request by EnomaDebby**
This was causing breaking changes

### CODE REVIEW

**Comment by ilyakatz** [comment]
ouch, my bad! @EnomaDebby

**Comment by EnomaDebby** [comment]
@rience @ilyakatz deployed to rubygems

**Comment by ilyakatz** [comment]
nice! thanks for the pr @rience and thanks @EnomaDebby for your first release!

**Comment by EnomaDebby** [comment]
Opps, this was the wrong PR :)

**Pull request merged**
