### PR TITLE
Status service fix migration files path

### PR DESCRIPTION
**Pull request by Haradd**
Hi,
there's a problem with `StatusService` when under `data_migrations_path` is specified absolute path containing another directory than `Rails.root`.

Exactly here:
https://github.com/ilyakatz/data-migrate/blob/47c6acaf98876ed8977a24478808055cd64fd63a/lib/data_migrate/status_service.rb#L55

`File.join` adds `root_folder` to the absolute path causing an inexistent path.

The solution is to provide by default full path in `data_migrations_path`.
What do you think about this? 🙂

### CODE REVIEW

**Comment by ilyakatz** [comment]
@EnomaDebby what do you think?

**Comment by EnomaDebby** [comment]
Hi @Haradd, trying to understand this problem. Are you not working from a rails app? Can you post screenshots of the problem to help us better understand?

**Comment by ilyakatz** [comment]
hi @Haradd is this still an issue?

**Comment by Haradd** [comment]
The issue is solved, thanks a lot!

**Pull request closed without merging**
