### PR TITLE
Fixes #199 - Fixed class name in `DataMigrate::Migration.check_pending!` 

### LINKED ISSUE #199: Error in `DataMigrate::Migration.check_pending!`?
I think I found a small typo in `DataMigrate::Migration.check_pending!` (located in `/lib/data_migrate/migration.rb`)

`DataMigrator::Migrator` should be `DataMigrator::DataMigrator`

So this:

https://github.com/ilyakatz/data-migrate/blob/1db042bfd1f29602dffe27b233e3261fa7eb7bb4/lib/data_migrate/migration.rb#L5-L7

should be:
```
 def check_pending!(connection = ::ActiveRecord::Base.connection) 
   raise ActiveRecord::PendingMigrationError if DataMigrator::Migrator.needs_migration?(connection) 
 end 
```

### PR DESCRIPTION
**Pull request by sully7**
`DataMigrator::Migrator.needs_migration?` should be `DataMigrator::DataMigrator.needs_migration?`

### CODE REVIEW

**Comment by sully7** [comment]
Fixes #200

**Comment by sully7** [comment]
Fixes #199

**Comment by ilyakatz** [comment]
Cool, thanks for finding this. I think this was an old name. Guess there were no tests for this. Do you think it's worth adding one?

**Comment by ilyakatz** [comment]
hi @sully7 are you still interested in completing this one?

**Comment by ilyakatz** [comment]
will close it out since there hasn't been any action

**Pull request closed without merging**
